// Class: ReadFish_QCD_CWoLa_Diff
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Fisher::Fish_QCD_CWoLa_Diff
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/04       [396292]
Creator        : viniciusmikuni
Date           : Tue Feb 20 18:56:52 2018
Host           : Darwin Viniciuss-MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
Dir            : /Users/viniciusmikuni/cernbox/CMS/ttbbAnalysis/KinFitter/test/MVA/BDT
Training events: 327123
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
Method: "Fisher" [Discrimination method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 22
top1_m                        top1_m                        top1_m                        top1_m                                                          'F'    [73.8372192383,288.592498779]
top2_m                        top2_m                        top2_m                        top2_m                                                          'F'    [67.5231781006,288.756622314]
w1_m                          w1_m                          w1_m                          w1_m                                                            'F'    [17.5459976196,175.533081055]
w2_m                          w2_m                          w2_m                          w2_m                                                            'F'    [18.4275913239,174.982009888]
deltaRb1b2                    deltaRb1b2                    deltaRb1b2                    deltaRb1b2                                                      'F'    [0,5.6260061264]
deltaRb1w1                    deltaRb1w1                    deltaRb1w1                    deltaRb1w1                                                      'F'    [0,7.88607883453]
deltaRb2w2                    deltaRb2w2                    deltaRb2w2                    deltaRb2w2                                                      'F'    [0,6.87519073486]
jet_CSV[0]                    jet_CSV_0_                    jet_CSV[0]                    jet_CSV[0]                                                      'F'    [0,1]
jet_CSV[1]                    jet_CSV_1_                    jet_CSV[1]                    jet_CSV[1]                                                      'F'    [0,1]
BDT_Comb                      BDT_Comb                      BDT_Comb                      BDT_Comb                                                        'F'    [-0.998443841934,0.988075017929]
simple_chi2                   simple_chi2                   simple_chi2                   simple_chi2                                                     'F'    [0.002432764275,33.3767547607]
meanDeltaRbtag                meanDeltaRbtag                meanDeltaRbtag                meanDeltaRbtag                                                  'F'    [0.390224814415,5.60265398026]
mindeltaRb1q                  mindeltaRb1q                  mindeltaRb1q                  mindeltaRb1q                                                    'F'    [0,3.8286626339]
mindeltaRb2p                  mindeltaRb2p                  mindeltaRb2p                  mindeltaRb2p                                                    'F'    [0,4.11091804504]
jet_CSV[2]                    jet_CSV_2_                    jet_CSV[2]                    jet_CSV[2]                                                      'F'    [0,0.999574363232]
jet_CSV[3]                    jet_CSV_3_                    jet_CSV[3]                    jet_CSV[3]                                                      'F'    [0,0.999629914761]
jet_CSV[4]                    jet_CSV_4_                    jet_CSV[4]                    jet_CSV[4]                                                      'F'    [0,0.9995200634]
jet_CSV[5]                    jet_CSV_5_                    jet_CSV[5]                    jet_CSV[5]                                                      'F'    [0,0.999631464481]
jets_dRmax                    jets_dRmax                    jets_dRmax                    jets_dRmax                                                      'F'    [1.93230545521,5.65536117554]
jets_dRavg                    jets_dRavg                    jets_dRavg                    jets_dRavg                                                      'F'    [0.963145196438,3.28623795509]
all_mass                      all_mass                      all_mass                      all_mass                                                        'F'    [445.707733154,6616.77001953]
closest_mass                  closest_mass                  closest_mass                  closest_mass                                                    'F'    [14.8440561295,117.368041992]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadFish_QCD_CWoLa_Diff : public IClassifierReader {

 public:

   // constructor
   ReadFish_QCD_CWoLa_Diff( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadFish_QCD_CWoLa_Diff" ),
        fNvars( 22 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "top1_m", "top2_m", "w1_m", "w2_m", "deltaRb1b2", "deltaRb1w1", "deltaRb2w2", "jet_CSV[0]", "jet_CSV[1]", "BDT_Comb", "simple_chi2", "meanDeltaRbtag", "mindeltaRb1q", "mindeltaRb2p", "jet_CSV[2]", "jet_CSV[3]", "jet_CSV[4]", "jet_CSV[5]", "jets_dRmax", "jets_dRavg", "all_mass", "closest_mass" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadFish_QCD_CWoLa_Diff() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[22];
   double fVmax[22];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[22];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   double              fFisher0;
   std::vector<double> fFisherCoefficients;
};

inline void ReadFish_QCD_CWoLa_Diff::Initialize() 
{
   fFisher0 = 0.249514092164;
   fFisherCoefficients.push_back( -5.17803383128e-05 );
   fFisherCoefficients.push_back( 0.000997337295688 );
   fFisherCoefficients.push_back( 0.00199364646297 );
   fFisherCoefficients.push_back( 0.00090828184775 );
   fFisherCoefficients.push_back( 0.0347488480808 );
   fFisherCoefficients.push_back( -0.0360958548569 );
   fFisherCoefficients.push_back( -0.0305993985265 );
   fFisherCoefficients.push_back( -0.30417860524 );
   fFisherCoefficients.push_back( -0.181768267932 );
   fFisherCoefficients.push_back( 0.398785135178 );
   fFisherCoefficients.push_back( -0.00744149313725 );
   fFisherCoefficients.push_back( 0.106708339092 );
   fFisherCoefficients.push_back( 0.00607098094054 );
   fFisherCoefficients.push_back( -0.0311718408086 );
   fFisherCoefficients.push_back( 0.011203682093 );
   fFisherCoefficients.push_back( 0.014797273557 );
   fFisherCoefficients.push_back( -0.021820112216 );
   fFisherCoefficients.push_back( -0.0227130916432 );
   fFisherCoefficients.push_back( -0.0556637568972 );
   fFisherCoefficients.push_back( -0.228737536447 );
   fFisherCoefficients.push_back( -1.62565781157e-05 );
   fFisherCoefficients.push_back( 0.00453976583439 );

   // sanity check
   if (fFisherCoefficients.size() != fNvars) {
      std::cout << "Problem in class \"" << fClassName << "\"::Initialize: mismatch in number of input values"
                << fFisherCoefficients.size() << " != " << fNvars << std::endl;
      fStatusIsClean = false;
   }         
}

inline double ReadFish_QCD_CWoLa_Diff::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double retval = fFisher0;
   for (size_t ivar = 0; ivar < fNvars; ivar++) {
      retval += fFisherCoefficients[ivar]*inputValues[ivar];
   }

   return retval;
}

// Clean up
inline void ReadFish_QCD_CWoLa_Diff::Clear() 
{
   // clear coefficients
   fFisherCoefficients.clear(); 
}
   inline double ReadFish_QCD_CWoLa_Diff::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
