// Class: ReadPyDNN_Multi_n_jets>=8
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : PyKeras::PyDNN_Multi_n_jets>=8
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/04       [396292]
Creator        : viniciusmikuni
Date           : Wed Mar  7 14:21:37 2018
Host           : Darwin Viniciuss-MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
Dir            : /Users/viniciusmikuni/cernbox/CMS/ttbbAnalysis/KinFitter/test/MVA/BDT
Training events: 335802
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
FilenameModel: "models/model_Multi_n_jets>=8.h5" [Filename of the initial Keras model]
BatchSize: "128" [Training batch size]
NumEpochs: "50" [Number of training epochs]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
FilenameTrainedModel: "MVA_weights/weights/TrainedModel_PyDNN_Multi_n_jets>=8.h5" [Filename of the trained output Keras model]
Verbose: "1" [Keras verbosity during training]
ContinueTraining: "False" [Load weights from previous training]
SaveBestOnly: "True" [Store only weights with smallest validation loss]
TriesEarlyStopping: "-1" [Number of epochs with no improvement in validation loss after which training will be stopped. The default or a negative number deactivates this option.]
LearningRateSchedule: "" [Set new learning rate during training at specific epochs, e.g., "50,0.01;70,0.005"]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 98
tt_pt                         tt_pt                         tt_pt                         tt_pt                                                           'F'    [0.361618250608,1406.95825195]
tt_phi                        tt_phi                        tt_phi                        tt_phi                                                          'F'    [-3.14156508446,3.14153432846]
tt_eta                        tt_eta                        tt_eta                        tt_eta                                                          'F'    [-7.50817918777,8.25331687927]
b1_phi                        b1_phi                        b1_phi                        b1_phi                                                          'F'    [-3.14153075218,3.14159250259]
b1_eta                        b1_eta                        b1_eta                        b1_eta                                                          'F'    [-2.39987015724,2.39986634254]
b2_phi                        b2_phi                        b2_phi                        b2_phi                                                          'F'    [-3.1415412426,3.14151978493]
b2_eta                        b2_eta                        b2_eta                        b2_eta                                                          'F'    [-2.39999675751,2.39999604225]
lq1_phi                       lq1_phi                       lq1_phi                       lq1_phi                                                         'F'    [-3.14157319069,3.14158034325]
lq2_phi                       lq2_phi                       lq2_phi                       lq2_phi                                                         'F'    [-3.14157581329,3.14157557487]
lp1_phi                       lp1_phi                       lp1_phi                       lp1_phi                                                         'F'    [-3.14158654213,3.14158439636]
lp2_phi                       lp2_phi                       lp2_phi                       lp2_phi                                                         'F'    [-3.14157366753,3.14157223701]
w1_m                          w1_m                          w1_m                          w1_m                                                            'F'    [17.4326934814,177.874359131]
w2_m                          w2_m                          w2_m                          w2_m                                                            'F'    [17.4640216827,179.545806885]
top1_m                        top1_m                        top1_m                        top1_m                                                          'F'    [64.8633041382,296.722900391]
top1_pt                       top1_pt                       top1_pt                       top1_pt                                                         'F'    [0.172712668777,1250.36657715]
top1_phi                      top1_phi                      top1_phi                      top1_phi                                                        'F'    [-3.1415681839,3.14158034325]
top2_m                        top2_m                        top2_m                        top2_m                                                          'F'    [62.0945663452,296.834625244]
top2_pt                       top2_pt                       top2_pt                       top2_pt                                                         'F'    [0.376397669315,1255.38452148]
top2_phi                      top2_phi                      top2_phi                      top2_phi                                                        'F'    [-3.14152002335,3.14156889915]
deltaRb1w1                    deltaRb1w1                    deltaRb1w1                    deltaRb1w1                                                      'F'    [0,8.97479438782]
deltaRb1w2                    deltaRb1w2                    deltaRb1w2                    deltaRb1w2                                                      'F'    [0,7.8408408165]
deltaPhiaddw1                 deltaPhiaddw1                 deltaPhiaddw1                 deltaPhiaddw1                                                   'F'    [-3.14155507088,3.14158129692]
deltaPhiaddw2                 deltaPhiaddw2                 deltaPhiaddw2                 deltaPhiaddw2                                                   'F'    [-3.14158797264,3.14158272743]
meanDeltaRbtag                meanDeltaRbtag                meanDeltaRbtag                meanDeltaRbtag                                                  'F'    [0.397755235434,5.39402532578]
prob_chi2                     prob_chi2                     prob_chi2                     prob_chi2                                                       'F'    [1.00009195592e-07,0.999999284744]
BDT_Comb                      BDT_Comb                      BDT_Comb                      BDT_Comb                                                        'F'    [-0.997296273708,0.992211997509]
deltaPhiaddtop1               deltaPhiaddtop1               deltaPhiaddtop1               deltaPhiaddtop1                                                 'F'    [-3.14158773422,3.14158582687]
deltaPhiaddtop2               deltaPhiaddtop2               deltaPhiaddtop2               deltaPhiaddtop2                                                 'F'    [-3.1415617466,3.14159035683]
deltaPhiq1q2                  deltaPhiq1q2                  deltaPhiq1q2                  deltaPhiq1q2                                                    'F'    [-3.14158844948,3.14088106155]
deltaPhiaddb2                 deltaPhiaddb2                 deltaPhiaddb2                 deltaPhiaddb2                                                   'F'    [-3.14159011841,3.14158987999]
deltaPhiaddb1                 deltaPhiaddb1                 deltaPhiaddb1                 deltaPhiaddb1                                                   'F'    [-3.14156937599,3.14158463478]
deltaRaddb1                   deltaRaddb1                   deltaRaddb1                   deltaRaddb1                                                     'F'    [0,5.58939981461]
deltaRaddb2                   deltaRaddb2                   deltaRaddb2                   deltaRaddb2                                                     'F'    [0,5.61952877045]
deltaPhit1t2                  deltaPhit1t2                  deltaPhit1t2                  deltaPhit1t2                                                    'F'    [-3.14159107208,3.14158987999]
deltaRb1q1                    deltaRb1q1                    deltaRb1q1                    deltaRb1q1                                                      'F'    [0,4.3060002327]
deltaRl1l2                    deltaRl1l2                    deltaRl1l2                    deltaRl1l2                                                      'F'    [0,4.07061862946]
btagLR4b                      btagLR4b                      btagLR4b                      btagLR4b                                                        'F'    [0.0355891250074,0.999983251095]
deltaRb2w2                    deltaRb2w2                    deltaRb2w2                    deltaRb2w2                                                      'F'    [0,7.92438650131]
deltaRb2w1                    deltaRb2w1                    deltaRb2w1                    deltaRb2w1                                                      'F'    [0,8.13176059723]
btagLR3b                      btagLR3b                      btagLR3b                      btagLR3b                                                        'F'    [0.230786755681,0.997069835663]
deltaEtaw1w2                  deltaEtaw1w2                  deltaEtaw1w2                  deltaEtaw1w2                                                    'F'    [-7.88465595245,8.42486763]
deltaRb1top2                  deltaRb1top2                  deltaRb1top2                  deltaRb1top2                                                    'F'    [0,9.22902679443]
mindeltaRb1q                  mindeltaRb1q                  mindeltaRb1q                  mindeltaRb1q                                                    'F'    [0,3.77048397064]
deltaRb2p1                    deltaRb2p1                    deltaRb2p1                    deltaRb2p1                                                      'F'    [0,4.57039880753]
deltaRb2top1                  deltaRb2top1                  deltaRb2top1                  deltaRb2top1                                                    'F'    [0,8.14050674438]
aplanarity                    aplanarity                    aplanarity                    aplanarity                                                      'F'    [0.000271515949862,0.458270043135]
p1b2_mass                     p1b2_mass                     p1b2_mass                     p1b2_mass                                                       'F'    [0,277.714935303]
centrality                    centrality                    centrality                    centrality                                                      'F'    [0.234268456697,0.970567166805]
deltaEtaq1q2                  deltaEtaq1q2                  deltaEtaq1q2                  deltaEtaq1q2                                                    'F'    [-2.86342167854,3.02313184738]
deltaPhil1l2                  deltaPhil1l2                  deltaPhil1l2                  deltaPhil1l2                                                    'F'    [-3.14111447334,3.14150977135]
deltaEtal1l2                  deltaEtal1l2                  deltaEtal1l2                  deltaEtal1l2                                                    'F'    [-2.9968123436,2.98849177361]
q1b1_mass                     q1b1_mass                     q1b1_mass                     q1b1_mass                                                       'F'    [0,279.830841064]
deltaRaddtop2                 deltaRaddtop2                 deltaRaddtop2                 deltaRaddtop2                                                   'F'    [0,8.14742660522]
deltaRaddtop1                 deltaRaddtop1                 deltaRaddtop1                 deltaRaddtop1                                                   'F'    [0,9.25780582428]
ht                            ht                            ht                            ht                                                              'F'    [500.004272461,4559.85253906]
deltaPhiw1w2                  deltaPhiw1w2                  deltaPhiw1w2                  deltaPhiw1w2                                                    'F'    [-3.1415772438,3.14157700539]
closest_mass                  closest_mass                  closest_mass                  closest_mass                                                    'F'    [14.7909955978,119.38747406]
deltaPhib1b2                  deltaPhib1b2                  deltaPhib1b2                  deltaPhib1b2                                                    'F'    [-3.14159107208,3.14157271385]
jets_dRavg                    jets_dRavg                    jets_dRavg                    jets_dRavg                                                      'F'    [0.996053338051,3.28654432297]
jets_dRmin                    jets_dRmin                    jets_dRmin                    jets_dRmin                                                      'F'    [0.380486577749,3.26467013359]
deltaEtab1b2                  deltaEtab1b2                  deltaEtab1b2                  deltaEtab1b2                                                    'F'    [-4.74190473557,4.66404771805]
meanCSV                       meanCSV                       meanCSV                       meanCSV                                                         'F'    [0.708085238934,0.99942612648]
deltaRb1b2                    deltaRb1b2                    deltaRb1b2                    deltaRb1b2                                                      'F'    [0,5.47591495514]
deltaRaddw2                   deltaRaddw2                   deltaRaddw2                   deltaRaddw2                                                     'F'    [0,8.55142498016]
deltaRaddw1                   deltaRaddw1                   deltaRaddw1                   deltaRaddw1                                                     'F'    [0,8.52830600739]
mindeltaRb2p                  mindeltaRb2p                  mindeltaRb2p                  mindeltaRb2p                                                    'F'    [0,4.03867006302]
meanCSVbtag                   meanCSVbtag                   meanCSVbtag                   meanCSVbtag                                                     'F'    [-2.20534467697,0.900753617287]
jets_dRmax                    jets_dRmax                    jets_dRmax                    jets_dRmax                                                      'F'    [2.14934945107,5.65025854111]
deltaEtat1t2                  deltaEtat1t2                  deltaEtat1t2                  deltaEtat1t2                                                    'F'    [-8.3444519043,9.20478534698]
deltaRq1q2                    deltaRq1q2                    deltaRq1q2                    deltaRq1q2                                                      'F'    [0,4.04936885834]
BDT_CWoLa                     BDT_CWoLa                     BDT_CWoLa                     BDT_CWoLa                                                       'F'    [-0.999770760536,0.999991118908]
addJet_CSV[0]                 addJet_CSV_0_                 addJet_CSV[0]                 addJet_CSV[0]                                                   'F'    [-10,0.99961233139]
addJet_pt[0]                  addJet_pt_0_                  addJet_pt[0]                  addJet_pt[0]                                                    'F'    [0,1967.90148926]
jet_QGL[0]                    jet_QGL_0_                    jet_QGL[0]                    jet_QGL[0]                                                      'F'    [0,1]
jet_QGL[1]                    jet_QGL_1_                    jet_QGL[1]                    jet_QGL[1]                                                      'F'    [0,1]
jet_QGL[2]                    jet_QGL_2_                    jet_QGL[2]                    jet_QGL[2]                                                      'F'    [0,1]
jet_QGL[3]                    jet_QGL_3_                    jet_QGL[3]                    jet_QGL[3]                                                      'F'    [0,1]
jet_QGL[4]                    jet_QGL_4_                    jet_QGL[4]                    jet_QGL[4]                                                      'F'    [0,1]
jet_QGL[5]                    jet_QGL_5_                    jet_QGL[5]                    jet_QGL[5]                                                      'F'    [0,1]
jet_CSV[1]                    jet_CSV_1_                    jet_CSV[1]                    jet_CSV[1]                                                      'F'    [0,1]
jet_CSV[2]                    jet_CSV_2_                    jet_CSV[2]                    jet_CSV[2]                                                      'F'    [0,0.999437868595]
jet_CSV[3]                    jet_CSV_3_                    jet_CSV[3]                    jet_CSV[3]                                                      'F'    [0,0.999525308609]
jet_CSV[4]                    jet_CSV_4_                    jet_CSV[4]                    jet_CSV[4]                                                      'F'    [0,0.99944037199]
jet_CSV[5]                    jet_CSV_5_                    jet_CSV[5]                    jet_CSV[5]                                                      'F'    [0,0.999549746513]
jet_MOverPt[0]                jet_MOverPt_0_                jet_MOverPt[0]                jet_MOverPt[0]                                                  'F'    [0,0.329929202795]
jet_MOverPt[1]                jet_MOverPt_1_                jet_MOverPt[1]                jet_MOverPt[1]                                                  'F'    [0,0.32913929224]
jet_MOverPt[2]                jet_MOverPt_2_                jet_MOverPt[2]                jet_MOverPt[2]                                                  'F'    [0,0.325283885002]
jet_MOverPt[3]                jet_MOverPt_3_                jet_MOverPt[3]                jet_MOverPt[3]                                                  'F'    [0,0.3262155056]
jet_MOverPt[4]                jet_MOverPt_4_                jet_MOverPt[4]                jet_MOverPt[4]                                                  'F'    [0,0.315746188164]
jet_MOverPt[5]                jet_MOverPt_5_                jet_MOverPt[5]                jet_MOverPt[5]                                                  'F'    [0,0.342738419771]
addJet_QGL[0]                 addJet_QGL_0_                 addJet_QGL[0]                 addJet_QGL[0]                                                   'F'    [-20,1]
addJet_deltaR                 addJet_deltaR                 addJet_deltaR                 addJet_deltaR                                                   'F'    [0,5.62844467163]
addJet_deltaPhi               addJet_deltaPhi               addJet_deltaPhi               addJet_deltaPhi                                                 'F'    [-3.14158272743,3.14156198502]
addJet_deltaEta               addJet_deltaEta               addJet_deltaEta               addJet_deltaEta                                                 'F'    [-4.7930560112,4.7903046608]
addJet_CSV[1]                 addJet_CSV_1_                 addJet_CSV[1]                 addJet_CSV[1]                                                   'F'    [-10,1]
addJet_pt[1]                  addJet_pt_1_                  addJet_pt[1]                  addJet_pt[1]                                                    'F'    [0,1765.5402832]
addJet_mass                   addJet_mass                   addJet_mass                   addJet_mass                                                     'F'    [0,4182.49707031]
addJet_QGL[1]                 addJet_QGL_1_                 addJet_QGL[1]                 addJet_QGL[1]                                                   'F'    [-20,1]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadPyDNN_Multi_n_jets>=8 : public IClassifierReader {

 public:

   // constructor
   ReadPyDNN_Multi_n_jets>=8( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadPyDNN_Multi_n_jets>=8" ),
        fNvars( 98 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "tt_pt", "tt_phi", "tt_eta", "b1_phi", "b1_eta", "b2_phi", "b2_eta", "lq1_phi", "lq2_phi", "lp1_phi", "lp2_phi", "w1_m", "w2_m", "top1_m", "top1_pt", "top1_phi", "top2_m", "top2_pt", "top2_phi", "deltaRb1w1", "deltaRb1w2", "deltaPhiaddw1", "deltaPhiaddw2", "meanDeltaRbtag", "prob_chi2", "BDT_Comb", "deltaPhiaddtop1", "deltaPhiaddtop2", "deltaPhiq1q2", "deltaPhiaddb2", "deltaPhiaddb1", "deltaRaddb1", "deltaRaddb2", "deltaPhit1t2", "deltaRb1q1", "deltaRl1l2", "btagLR4b", "deltaRb2w2", "deltaRb2w1", "btagLR3b", "deltaEtaw1w2", "deltaRb1top2", "mindeltaRb1q", "deltaRb2p1", "deltaRb2top1", "aplanarity", "p1b2_mass", "centrality", "deltaEtaq1q2", "deltaPhil1l2", "deltaEtal1l2", "q1b1_mass", "deltaRaddtop2", "deltaRaddtop1", "ht", "deltaPhiw1w2", "closest_mass", "deltaPhib1b2", "jets_dRavg", "jets_dRmin", "deltaEtab1b2", "meanCSV", "deltaRb1b2", "deltaRaddw2", "deltaRaddw1", "mindeltaRb2p", "meanCSVbtag", "jets_dRmax", "deltaEtat1t2", "deltaRq1q2", "BDT_CWoLa", "addJet_CSV[0]", "addJet_pt[0]", "jet_QGL[0]", "jet_QGL[1]", "jet_QGL[2]", "jet_QGL[3]", "jet_QGL[4]", "jet_QGL[5]", "jet_CSV[1]", "jet_CSV[2]", "jet_CSV[3]", "jet_CSV[4]", "jet_CSV[5]", "jet_MOverPt[0]", "jet_MOverPt[1]", "jet_MOverPt[2]", "jet_MOverPt[3]", "jet_MOverPt[4]", "jet_MOverPt[5]", "addJet_QGL[0]", "addJet_deltaR", "addJet_deltaPhi", "addJet_deltaEta", "addJet_CSV[1]", "addJet_pt[1]", "addJet_mass", "addJet_QGL[1]" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;
      fVmin[32] = 0;
      fVmax[32] = 0;
      fVmin[33] = 0;
      fVmax[33] = 0;
      fVmin[34] = 0;
      fVmax[34] = 0;
      fVmin[35] = 0;
      fVmax[35] = 0;
      fVmin[36] = 0;
      fVmax[36] = 0;
      fVmin[37] = 0;
      fVmax[37] = 0;
      fVmin[38] = 0;
      fVmax[38] = 0;
      fVmin[39] = 0;
      fVmax[39] = 0;
      fVmin[40] = 0;
      fVmax[40] = 0;
      fVmin[41] = 0;
      fVmax[41] = 0;
      fVmin[42] = 0;
      fVmax[42] = 0;
      fVmin[43] = 0;
      fVmax[43] = 0;
      fVmin[44] = 0;
      fVmax[44] = 0;
      fVmin[45] = 0;
      fVmax[45] = 0;
      fVmin[46] = 0;
      fVmax[46] = 0;
      fVmin[47] = 0;
      fVmax[47] = 0;
      fVmin[48] = 0;
      fVmax[48] = 0;
      fVmin[49] = 0;
      fVmax[49] = 0;
      fVmin[50] = 0;
      fVmax[50] = 0;
      fVmin[51] = 0;
      fVmax[51] = 0;
      fVmin[52] = 0;
      fVmax[52] = 0;
      fVmin[53] = 0;
      fVmax[53] = 0;
      fVmin[54] = 0;
      fVmax[54] = 0;
      fVmin[55] = 0;
      fVmax[55] = 0;
      fVmin[56] = 0;
      fVmax[56] = 0;
      fVmin[57] = 0;
      fVmax[57] = 0;
      fVmin[58] = 0;
      fVmax[58] = 0;
      fVmin[59] = 0;
      fVmax[59] = 0;
      fVmin[60] = 0;
      fVmax[60] = 0;
      fVmin[61] = 0;
      fVmax[61] = 0;
      fVmin[62] = 0;
      fVmax[62] = 0;
      fVmin[63] = 0;
      fVmax[63] = 0;
      fVmin[64] = 0;
      fVmax[64] = 0;
      fVmin[65] = 0;
      fVmax[65] = 0;
      fVmin[66] = 0;
      fVmax[66] = 0;
      fVmin[67] = 0;
      fVmax[67] = 0;
      fVmin[68] = 0;
      fVmax[68] = 0;
      fVmin[69] = 0;
      fVmax[69] = 0;
      fVmin[70] = 0;
      fVmax[70] = 0;
      fVmin[71] = 0;
      fVmax[71] = 0;
      fVmin[72] = 0;
      fVmax[72] = 0;
      fVmin[73] = 0;
      fVmax[73] = 0;
      fVmin[74] = 0;
      fVmax[74] = 0;
      fVmin[75] = 0;
      fVmax[75] = 0;
      fVmin[76] = 0;
      fVmax[76] = 0;
      fVmin[77] = 0;
      fVmax[77] = 0;
      fVmin[78] = 0;
      fVmax[78] = 0;
      fVmin[79] = 0;
      fVmax[79] = 0;
      fVmin[80] = 0;
      fVmax[80] = 0;
      fVmin[81] = 0;
      fVmax[81] = 0;
      fVmin[82] = 0;
      fVmax[82] = 0;
      fVmin[83] = 0;
      fVmax[83] = 0;
      fVmin[84] = 0;
      fVmax[84] = 0;
      fVmin[85] = 0;
      fVmax[85] = 0;
      fVmin[86] = 0;
      fVmax[86] = 0;
      fVmin[87] = 0;
      fVmax[87] = 0;
      fVmin[88] = 0;
      fVmax[88] = 0;
      fVmin[89] = 0;
      fVmax[89] = 0;
      fVmin[90] = 0;
      fVmax[90] = 0;
      fVmin[91] = 0;
      fVmax[91] = 0;
      fVmin[92] = 0;
      fVmax[92] = 0;
      fVmin[93] = 0;
      fVmax[93] = 0;
      fVmin[94] = 0;
      fVmax[94] = 0;
      fVmin[95] = 0;
      fVmax[95] = 0;
      fVmin[96] = 0;
      fVmax[96] = 0;
      fVmin[97] = 0;
      fVmax[97] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';
      fType[37] = 'F';
      fType[38] = 'F';
      fType[39] = 'F';
      fType[40] = 'F';
      fType[41] = 'F';
      fType[42] = 'F';
      fType[43] = 'F';
      fType[44] = 'F';
      fType[45] = 'F';
      fType[46] = 'F';
      fType[47] = 'F';
      fType[48] = 'F';
      fType[49] = 'F';
      fType[50] = 'F';
      fType[51] = 'F';
      fType[52] = 'F';
      fType[53] = 'F';
      fType[54] = 'F';
      fType[55] = 'F';
      fType[56] = 'F';
      fType[57] = 'F';
      fType[58] = 'F';
      fType[59] = 'F';
      fType[60] = 'F';
      fType[61] = 'F';
      fType[62] = 'F';
      fType[63] = 'F';
      fType[64] = 'F';
      fType[65] = 'F';
      fType[66] = 'F';
      fType[67] = 'F';
      fType[68] = 'F';
      fType[69] = 'F';
      fType[70] = 'F';
      fType[71] = 'F';
      fType[72] = 'F';
      fType[73] = 'F';
      fType[74] = 'F';
      fType[75] = 'F';
      fType[76] = 'F';
      fType[77] = 'F';
      fType[78] = 'F';
      fType[79] = 'F';
      fType[80] = 'F';
      fType[81] = 'F';
      fType[82] = 'F';
      fType[83] = 'F';
      fType[84] = 'F';
      fType[85] = 'F';
      fType[86] = 'F';
      fType[87] = 'F';
      fType[88] = 'F';
      fType[89] = 'F';
      fType[90] = 'F';
      fType[91] = 'F';
      fType[92] = 'F';
      fType[93] = 'F';
      fType[94] = 'F';
      fType[95] = 'F';
      fType[96] = 'F';
      fType[97] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadPyDNN_Multi_n_jets>=8() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[98];
   double fVmax[98];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[98];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   inline double ReadPyDNN_Multi_n_jets>=8::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
