// Class: ReadPyDNN_Multi_n_jets==7
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : PyKeras::PyDNN_Multi_n_jets==7
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/04       [396292]
Creator        : viniciusmikuni
Date           : Wed Mar  7 12:51:34 2018
Host           : Darwin Viniciuss-MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
Dir            : /Users/viniciusmikuni/cernbox/CMS/ttbbAnalysis/KinFitter/test/MVA/BDT
Training events: 292005
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
FilenameModel: "models/model_Multi_n_jets==7.h5" [Filename of the initial Keras model]
BatchSize: "128" [Training batch size]
NumEpochs: "50" [Number of training epochs]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
FilenameTrainedModel: "MVA_weights/weights/TrainedModel_PyDNN_Multi_n_jets==7.h5" [Filename of the trained output Keras model]
Verbose: "1" [Keras verbosity during training]
ContinueTraining: "False" [Load weights from previous training]
SaveBestOnly: "True" [Store only weights with smallest validation loss]
TriesEarlyStopping: "-1" [Number of epochs with no improvement in validation loss after which training will be stopped. The default or a negative number deactivates this option.]
LearningRateSchedule: "" [Set new learning rate during training at specific epochs, e.g., "50,0.01;70,0.005"]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 91
tt_pt                         tt_pt                         tt_pt                         tt_pt                                                           'F'    [0.479255348444,1361.37475586]
tt_phi                        tt_phi                        tt_phi                        tt_phi                                                          'F'    [-3.14158415794,3.14157748222]
tt_eta                        tt_eta                        tt_eta                        tt_eta                                                          'F'    [-7.23454856873,7.60782670975]
b1_phi                        b1_phi                        b1_phi                        b1_phi                                                          'F'    [-3.14151215553,3.14158344269]
b1_eta                        b1_eta                        b1_eta                        b1_eta                                                          'F'    [-2.39986419678,2.39986586571]
b2_phi                        b2_phi                        b2_phi                        b2_phi                                                          'F'    [-3.14158153534,3.14148759842]
b2_eta                        b2_eta                        b2_eta                        b2_eta                                                          'F'    [-2.39996480942,2.39982271194]
lq1_phi                       lq1_phi                       lq1_phi                       lq1_phi                                                         'F'    [-3.14158630371,3.14158248901]
lq2_phi                       lq2_phi                       lq2_phi                       lq2_phi                                                         'F'    [-3.14156889915,3.14159154892]
lp1_phi                       lp1_phi                       lp1_phi                       lp1_phi                                                         'F'    [-3.14158535004,3.14159107208]
lp2_phi                       lp2_phi                       lp2_phi                       lp2_phi                                                         'F'    [-3.1415848732,3.14157581329]
w1_m                          w1_m                          w1_m                          w1_m                                                            'F'    [17.7709007263,180.971481323]
w2_m                          w2_m                          w2_m                          w2_m                                                            'F'    [17.5459976196,180.734359741]
top1_m                        top1_m                        top1_m                        top1_m                                                          'F'    [65.6817092896,296.845062256]
top1_pt                       top1_pt                       top1_pt                       top1_pt                                                         'F'    [0.850791811943,1383.01147461]
top1_phi                      top1_phi                      top1_phi                      top1_phi                                                        'F'    [-3.1415617466,3.14159274101]
top2_m                        top2_m                        top2_m                        top2_m                                                          'F'    [60.4324111938,296.766967773]
top2_pt                       top2_pt                       top2_pt                       top2_pt                                                         'F'    [0.715295493603,865.203613281]
top2_phi                      top2_phi                      top2_phi                      top2_phi                                                        'F'    [-3.14157962799,3.14156460762]
deltaRb1w1                    deltaRb1w1                    deltaRb1w1                    deltaRb1w1                                                      'F'    [0.00327018578537,5.81962156296]
deltaRb1w2                    deltaRb1w2                    deltaRb1w2                    deltaRb1w2                                                      'F'    [0.00527415098622,7.10530757904]
deltaPhiaddw1                 deltaPhiaddw1                 deltaPhiaddw1                 deltaPhiaddw1                                                   'F'    [-3.14155435562,3.14157748222]
deltaPhiaddw2                 deltaPhiaddw2                 deltaPhiaddw2                 deltaPhiaddw2                                                   'F'    [-3.14154100418,3.14159274101]
meanDeltaRbtag                meanDeltaRbtag                meanDeltaRbtag                meanDeltaRbtag                                                  'F'    [0.395938187838,5.12947750092]
prob_chi2                     prob_chi2                     prob_chi2                     prob_chi2                                                       'F'    [1.00002672809e-07,0.999997854233]
BDT_Comb                      BDT_Comb                      BDT_Comb                      BDT_Comb                                                        'F'    [-0.997236430645,0.977149367332]
deltaPhiaddtop1               deltaPhiaddtop1               deltaPhiaddtop1               deltaPhiaddtop1                                                 'F'    [-3.14158725739,3.14158725739]
deltaPhiaddtop2               deltaPhiaddtop2               deltaPhiaddtop2               deltaPhiaddtop2                                                 'F'    [-3.14157032967,3.14157319069]
deltaPhiq1q2                  deltaPhiq1q2                  deltaPhiq1q2                  deltaPhiq1q2                                                    'F'    [-3.14152979851,3.14155030251]
deltaPhiaddb2                 deltaPhiaddb2                 deltaPhiaddb2                 deltaPhiaddb2                                                   'F'    [-3.14157795906,3.14156603813]
deltaPhiaddb1                 deltaPhiaddb1                 deltaPhiaddb1                 deltaPhiaddb1                                                   'F'    [-3.14158844948,3.14157867432]
deltaRaddb1                   deltaRaddb1                   deltaRaddb1                   deltaRaddb1                                                     'F'    [0.392043322325,5.55965423584]
deltaRaddb2                   deltaRaddb2                   deltaRaddb2                   deltaRaddb2                                                     'F'    [0.397124797106,5.62597036362]
deltaPhit1t2                  deltaPhit1t2                  deltaPhit1t2                  deltaPhit1t2                                                    'F'    [-3.14159250259,3.14158940315]
deltaRb1q1                    deltaRb1q1                    deltaRb1q1                    deltaRb1q1                                                      'F'    [0.392151325941,4.13411474228]
deltaRl1l2                    deltaRl1l2                    deltaRl1l2                    deltaRl1l2                                                      'F'    [0.384431868792,4.22417116165]
btagLR4b                      btagLR4b                      btagLR4b                      btagLR4b                                                        'F'    [0.0191592704505,0.999986946583]
deltaRb2w2                    deltaRb2w2                    deltaRb2w2                    deltaRb2w2                                                      'F'    [0.0104066273198,7.18167448044]
deltaRb2w1                    deltaRb2w1                    deltaRb2w1                    deltaRb2w1                                                      'F'    [0.012636365369,8.05455303192]
btagLR3b                      btagLR3b                      btagLR3b                      btagLR3b                                                        'F'    [0.180406391621,0.997339427471]
deltaEtaw1w2                  deltaEtaw1w2                  deltaEtaw1w2                  deltaEtaw1w2                                                    'F'    [-8.01701259613,7.63670825958]
deltaRb1top2                  deltaRb1top2                  deltaRb1top2                  deltaRb1top2                                                    'F'    [0.0188910588622,8.52601528168]
mindeltaRb1q                  mindeltaRb1q                  mindeltaRb1q                  mindeltaRb1q                                                    'F'    [0.387666106224,3.62251448631]
deltaRb2p1                    deltaRb2p1                    deltaRb2p1                    deltaRb2p1                                                      'F'    [0.399683952332,4.5168800354]
deltaRb2top1                  deltaRb2top1                  deltaRb2top1                  deltaRb2top1                                                    'F'    [0.00273754168302,7.98906707764]
aplanarity                    aplanarity                    aplanarity                    aplanarity                                                      'F'    [0.000349903100869,0.435430467129]
p1b2_mass                     p1b2_mass                     p1b2_mass                     p1b2_mass                                                       'F'    [20.6188259125,278.542755127]
centrality                    centrality                    centrality                    centrality                                                      'F'    [0.219627931714,0.990948557854]
deltaEtaq1q2                  deltaEtaq1q2                  deltaEtaq1q2                  deltaEtaq1q2                                                    'F'    [-3.04183721542,3.00225567818]
deltaPhil1l2                  deltaPhil1l2                  deltaPhil1l2                  deltaPhil1l2                                                    'F'    [-3.14158940315,3.14154314995]
deltaEtal1l2                  deltaEtal1l2                  deltaEtal1l2                  deltaEtal1l2                                                    'F'    [-3.01611471176,2.85266017914]
q1b1_mass                     q1b1_mass                     q1b1_mass                     q1b1_mass                                                       'F'    [27.5939083099,279.436340332]
deltaRaddtop2                 deltaRaddtop2                 deltaRaddtop2                 deltaRaddtop2                                                   'F'    [0.0121795106679,8.76931858063]
deltaRaddtop1                 deltaRaddtop1                 deltaRaddtop1                 deltaRaddtop1                                                   'F'    [0.0102610196918,8.40252304077]
ht                            ht                            ht                            ht                                                              'F'    [500.001708984,2828.50488281]
deltaPhiw1w2                  deltaPhiw1w2                  deltaPhiw1w2                  deltaPhiw1w2                                                    'F'    [-3.14158320427,3.14158964157]
closest_mass                  closest_mass                  closest_mass                  closest_mass                                                    'F'    [17.0121002197,124.563194275]
deltaPhib1b2                  deltaPhib1b2                  deltaPhib1b2                  deltaPhib1b2                                                    'F'    [-3.14158821106,3.14158630371]
jets_dRavg                    jets_dRavg                    jets_dRavg                    jets_dRavg                                                      'F'    [0.85890775919,3.0150551796]
jets_dRmin                    jets_dRmin                    jets_dRmin                    jets_dRmin                                                      'F'    [0.386271297932,3.28987360001]
deltaEtab1b2                  deltaEtab1b2                  deltaEtab1b2                  deltaEtab1b2                                                    'F'    [-4.75107336044,4.77743387222]
meanCSV                       meanCSV                       meanCSV                       meanCSV                                                         'F'    [0.709745049477,0.999428749084]
deltaRb1b2                    deltaRb1b2                    deltaRb1b2                    deltaRb1b2                                                      'F'    [0.392987132072,5.41162157059]
deltaRaddw2                   deltaRaddw2                   deltaRaddw2                   deltaRaddw2                                                     'F'    [0.0135376406834,9.39756774902]
deltaRaddw1                   deltaRaddw1                   deltaRaddw1                   deltaRaddw1                                                     'F'    [0.00130801508203,8.40328407288]
mindeltaRb2p                  mindeltaRb2p                  mindeltaRb2p                  mindeltaRb2p                                                    'F'    [0.386538505554,4.16353368759]
meanCSVbtag                   meanCSVbtag                   meanCSVbtag                   meanCSVbtag                                                     'F'    [-1.13277435303,0.958395957947]
jets_dRmax                    jets_dRmax                    jets_dRmax                    jets_dRmax                                                      'F'    [1.74853420258,5.662317276]
deltaEtat1t2                  deltaEtat1t2                  deltaEtat1t2                  deltaEtat1t2                                                    'F'    [-8.0552110672,8.30740070343]
deltaRq1q2                    deltaRq1q2                    deltaRq1q2                    deltaRq1q2                                                      'F'    [0.385301887989,4.10242080688]
BDT_CWoLa                     BDT_CWoLa                     BDT_CWoLa                     BDT_CWoLa                                                       'F'    [-0.9997433424,0.999992370605]
addJet_CSV[0]                 addJet_CSV_0_                 addJet_CSV[0]                 addJet_CSV[0]                                                   'F'    [-10,0.99961411953]
addJet_pt[0]                  addJet_pt_0_                  addJet_pt[0]                  addJet_pt[0]                                                    'F'    [30.0002422333,1418.39526367]
jet_QGL[0]                    jet_QGL_0_                    jet_QGL[0]                    jet_QGL[0]                                                      'F'    [1.00300601158e-09,1]
jet_QGL[1]                    jet_QGL_1_                    jet_QGL[1]                    jet_QGL[1]                                                      'F'    [1.00300601158e-09,1]
jet_QGL[2]                    jet_QGL_2_                    jet_QGL[2]                    jet_QGL[2]                                                      'F'    [1.00300601158e-09,1]
jet_QGL[3]                    jet_QGL_3_                    jet_QGL[3]                    jet_QGL[3]                                                      'F'    [1.00300601158e-09,1]
jet_QGL[4]                    jet_QGL_4_                    jet_QGL[4]                    jet_QGL[4]                                                      'F'    [1.00300601158e-09,1]
jet_QGL[5]                    jet_QGL_5_                    jet_QGL[5]                    jet_QGL[5]                                                      'F'    [1.00300601158e-09,1]
jet_CSV[1]                    jet_CSV_1_                    jet_CSV[1]                    jet_CSV[1]                                                      'F'    [0.0430419445038,0.999632775784]
jet_CSV[2]                    jet_CSV_2_                    jet_CSV[2]                    jet_CSV[2]                                                      'F'    [0.0341643430293,0.999444901943]
jet_CSV[3]                    jet_CSV_3_                    jet_CSV[3]                    jet_CSV[3]                                                      'F'    [0.0375378541648,0.999551951885]
jet_CSV[4]                    jet_CSV_4_                    jet_CSV[4]                    jet_CSV[4]                                                      'F'    [0.0360015779734,0.999583423138]
jet_CSV[5]                    jet_CSV_5_                    jet_CSV[5]                    jet_CSV[5]                                                      'F'    [0.0335376374424,0.999505221844]
jet_MOverPt[0]                jet_MOverPt_0_                jet_MOverPt[0]                jet_MOverPt[0]                                                  'F'    [0.0104452371597,0.315320521593]
jet_MOverPt[1]                jet_MOverPt_1_                jet_MOverPt[1]                jet_MOverPt[1]                                                  'F'    [0.0222006831318,0.324985206127]
jet_MOverPt[2]                jet_MOverPt_2_                jet_MOverPt[2]                jet_MOverPt[2]                                                  'F'    [0.0226950012147,0.309670746326]
jet_MOverPt[3]                jet_MOverPt_3_                jet_MOverPt[3]                jet_MOverPt[3]                                                  'F'    [0.00592556875199,0.349254757166]
jet_MOverPt[4]                jet_MOverPt_4_                jet_MOverPt[4]                jet_MOverPt[4]                                                  'F'    [0.0114026376978,0.315707176924]
jet_MOverPt[5]                jet_MOverPt_5_                jet_MOverPt[5]                jet_MOverPt[5]                                                  'F'    [0.0147417737171,0.331616908312]
addJet_QGL[0]                 addJet_QGL_0_                 addJet_QGL[0]                 addJet_QGL[0]                                                   'F'    [-20,1]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadPyDNN_Multi_n_jets==7 : public IClassifierReader {

 public:

   // constructor
   ReadPyDNN_Multi_n_jets==7( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadPyDNN_Multi_n_jets==7" ),
        fNvars( 91 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "tt_pt", "tt_phi", "tt_eta", "b1_phi", "b1_eta", "b2_phi", "b2_eta", "lq1_phi", "lq2_phi", "lp1_phi", "lp2_phi", "w1_m", "w2_m", "top1_m", "top1_pt", "top1_phi", "top2_m", "top2_pt", "top2_phi", "deltaRb1w1", "deltaRb1w2", "deltaPhiaddw1", "deltaPhiaddw2", "meanDeltaRbtag", "prob_chi2", "BDT_Comb", "deltaPhiaddtop1", "deltaPhiaddtop2", "deltaPhiq1q2", "deltaPhiaddb2", "deltaPhiaddb1", "deltaRaddb1", "deltaRaddb2", "deltaPhit1t2", "deltaRb1q1", "deltaRl1l2", "btagLR4b", "deltaRb2w2", "deltaRb2w1", "btagLR3b", "deltaEtaw1w2", "deltaRb1top2", "mindeltaRb1q", "deltaRb2p1", "deltaRb2top1", "aplanarity", "p1b2_mass", "centrality", "deltaEtaq1q2", "deltaPhil1l2", "deltaEtal1l2", "q1b1_mass", "deltaRaddtop2", "deltaRaddtop1", "ht", "deltaPhiw1w2", "closest_mass", "deltaPhib1b2", "jets_dRavg", "jets_dRmin", "deltaEtab1b2", "meanCSV", "deltaRb1b2", "deltaRaddw2", "deltaRaddw1", "mindeltaRb2p", "meanCSVbtag", "jets_dRmax", "deltaEtat1t2", "deltaRq1q2", "BDT_CWoLa", "addJet_CSV[0]", "addJet_pt[0]", "jet_QGL[0]", "jet_QGL[1]", "jet_QGL[2]", "jet_QGL[3]", "jet_QGL[4]", "jet_QGL[5]", "jet_CSV[1]", "jet_CSV[2]", "jet_CSV[3]", "jet_CSV[4]", "jet_CSV[5]", "jet_MOverPt[0]", "jet_MOverPt[1]", "jet_MOverPt[2]", "jet_MOverPt[3]", "jet_MOverPt[4]", "jet_MOverPt[5]", "addJet_QGL[0]" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;
      fVmin[32] = 0;
      fVmax[32] = 0;
      fVmin[33] = 0;
      fVmax[33] = 0;
      fVmin[34] = 0;
      fVmax[34] = 0;
      fVmin[35] = 0;
      fVmax[35] = 0;
      fVmin[36] = 0;
      fVmax[36] = 0;
      fVmin[37] = 0;
      fVmax[37] = 0;
      fVmin[38] = 0;
      fVmax[38] = 0;
      fVmin[39] = 0;
      fVmax[39] = 0;
      fVmin[40] = 0;
      fVmax[40] = 0;
      fVmin[41] = 0;
      fVmax[41] = 0;
      fVmin[42] = 0;
      fVmax[42] = 0;
      fVmin[43] = 0;
      fVmax[43] = 0;
      fVmin[44] = 0;
      fVmax[44] = 0;
      fVmin[45] = 0;
      fVmax[45] = 0;
      fVmin[46] = 0;
      fVmax[46] = 0;
      fVmin[47] = 0;
      fVmax[47] = 0;
      fVmin[48] = 0;
      fVmax[48] = 0;
      fVmin[49] = 0;
      fVmax[49] = 0;
      fVmin[50] = 0;
      fVmax[50] = 0;
      fVmin[51] = 0;
      fVmax[51] = 0;
      fVmin[52] = 0;
      fVmax[52] = 0;
      fVmin[53] = 0;
      fVmax[53] = 0;
      fVmin[54] = 0;
      fVmax[54] = 0;
      fVmin[55] = 0;
      fVmax[55] = 0;
      fVmin[56] = 0;
      fVmax[56] = 0;
      fVmin[57] = 0;
      fVmax[57] = 0;
      fVmin[58] = 0;
      fVmax[58] = 0;
      fVmin[59] = 0;
      fVmax[59] = 0;
      fVmin[60] = 0;
      fVmax[60] = 0;
      fVmin[61] = 0;
      fVmax[61] = 0;
      fVmin[62] = 0;
      fVmax[62] = 0;
      fVmin[63] = 0;
      fVmax[63] = 0;
      fVmin[64] = 0;
      fVmax[64] = 0;
      fVmin[65] = 0;
      fVmax[65] = 0;
      fVmin[66] = 0;
      fVmax[66] = 0;
      fVmin[67] = 0;
      fVmax[67] = 0;
      fVmin[68] = 0;
      fVmax[68] = 0;
      fVmin[69] = 0;
      fVmax[69] = 0;
      fVmin[70] = 0;
      fVmax[70] = 0;
      fVmin[71] = 0;
      fVmax[71] = 0;
      fVmin[72] = 0;
      fVmax[72] = 0;
      fVmin[73] = 0;
      fVmax[73] = 0;
      fVmin[74] = 0;
      fVmax[74] = 0;
      fVmin[75] = 0;
      fVmax[75] = 0;
      fVmin[76] = 0;
      fVmax[76] = 0;
      fVmin[77] = 0;
      fVmax[77] = 0;
      fVmin[78] = 0;
      fVmax[78] = 0;
      fVmin[79] = 0;
      fVmax[79] = 0;
      fVmin[80] = 0;
      fVmax[80] = 0;
      fVmin[81] = 0;
      fVmax[81] = 0;
      fVmin[82] = 0;
      fVmax[82] = 0;
      fVmin[83] = 0;
      fVmax[83] = 0;
      fVmin[84] = 0;
      fVmax[84] = 0;
      fVmin[85] = 0;
      fVmax[85] = 0;
      fVmin[86] = 0;
      fVmax[86] = 0;
      fVmin[87] = 0;
      fVmax[87] = 0;
      fVmin[88] = 0;
      fVmax[88] = 0;
      fVmin[89] = 0;
      fVmax[89] = 0;
      fVmin[90] = 0;
      fVmax[90] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';
      fType[37] = 'F';
      fType[38] = 'F';
      fType[39] = 'F';
      fType[40] = 'F';
      fType[41] = 'F';
      fType[42] = 'F';
      fType[43] = 'F';
      fType[44] = 'F';
      fType[45] = 'F';
      fType[46] = 'F';
      fType[47] = 'F';
      fType[48] = 'F';
      fType[49] = 'F';
      fType[50] = 'F';
      fType[51] = 'F';
      fType[52] = 'F';
      fType[53] = 'F';
      fType[54] = 'F';
      fType[55] = 'F';
      fType[56] = 'F';
      fType[57] = 'F';
      fType[58] = 'F';
      fType[59] = 'F';
      fType[60] = 'F';
      fType[61] = 'F';
      fType[62] = 'F';
      fType[63] = 'F';
      fType[64] = 'F';
      fType[65] = 'F';
      fType[66] = 'F';
      fType[67] = 'F';
      fType[68] = 'F';
      fType[69] = 'F';
      fType[70] = 'F';
      fType[71] = 'F';
      fType[72] = 'F';
      fType[73] = 'F';
      fType[74] = 'F';
      fType[75] = 'F';
      fType[76] = 'F';
      fType[77] = 'F';
      fType[78] = 'F';
      fType[79] = 'F';
      fType[80] = 'F';
      fType[81] = 'F';
      fType[82] = 'F';
      fType[83] = 'F';
      fType[84] = 'F';
      fType[85] = 'F';
      fType[86] = 'F';
      fType[87] = 'F';
      fType[88] = 'F';
      fType[89] = 'F';
      fType[90] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadPyDNN_Multi_n_jets==7() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[91];
   double fVmax[91];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[91];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   inline double ReadPyDNN_Multi_n_jets==7::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
