// Class: ReadPyDNN_Multi_n_bjets>=5
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : PyKeras::PyDNN_Multi_n_bjets>=5
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/04       [396292]
Creator        : viniciusmikuni
Date           : Thu Mar  1 23:42:24 2018
Host           : Darwin Viniciuss-MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
Dir            : /Users/viniciusmikuni/cernbox/CMS/ttbbAnalysis/KinFitter/test/MVA/BDT
Training events: 1041
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
FilenameModel: "models/model_Multi_n_bjets>=5.h5" [Filename of the initial Keras model]
BatchSize: "128" [Training batch size]
NumEpochs: "50" [Number of training epochs]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
FilenameTrainedModel: "MVA_weights/weights/TrainedModel_PyDNN_Multi_n_bjets>=5.h5" [Filename of the trained output Keras model]
Verbose: "1" [Keras verbosity during training]
ContinueTraining: "False" [Load weights from previous training]
SaveBestOnly: "True" [Store only weights with smallest validation loss]
TriesEarlyStopping: "-1" [Number of epochs with no improvement in validation loss after which training will be stopped. The default or a negative number deactivates this option.]
LearningRateSchedule: "" [Set new learning rate during training at specific epochs, e.g., "50,0.01;70,0.005"]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 96
tt_m                          tt_m                          tt_m                          tt_m                                                            'F'    [319.316070557,1949.6484375]
tt_pt                         tt_pt                         tt_pt                         tt_pt                                                           'F'    [4.72126245499,771.44543457]
tt_phi                        tt_phi                        tt_phi                        tt_phi                                                          'F'    [-3.14104151726,3.1413769722]
tt_eta                        tt_eta                        tt_eta                        tt_eta                                                          'F'    [-4.97905349731,5.0586977005]
b1_phi                        b1_phi                        b1_phi                        b1_phi                                                          'F'    [-3.13576865196,3.1404876709]
b1_eta                        b1_eta                        b1_eta                        b1_eta                                                          'F'    [-2.36027598381,2.39780902863]
b2_phi                        b2_phi                        b2_phi                        b2_phi                                                          'F'    [-3.13665270805,3.13571643829]
b2_eta                        b2_eta                        b2_eta                        b2_eta                                                          'F'    [-2.36856150627,2.38760185242]
lq1_phi                       lq1_phi                       lq1_phi                       lq1_phi                                                         'F'    [-3.13587331772,3.13760972023]
lq2_phi                       lq2_phi                       lq2_phi                       lq2_phi                                                         'F'    [-3.1414141655,3.13945031166]
lp1_phi                       lp1_phi                       lp1_phi                       lp1_phi                                                         'F'    [-3.13316750526,3.13906741142]
lp2_phi                       lp2_phi                       lp2_phi                       lp2_phi                                                         'F'    [-3.13309431076,3.12897467613]
w1_m                          w1_m                          w1_m                          w1_m                                                            'F'    [27.0291309357,157.456970215]
w1_phi                        w1_phi                        w1_phi                        w1_phi                                                          'F'    [-3.14047336578,3.14040589333]
w2_m                          w2_m                          w2_m                          w2_m                                                            'F'    [29.0512104034,158.23638916]
w2_phi                        w2_phi                        w2_phi                        w2_phi                                                          'F'    [-3.13096547127,3.13964772224]
top1_m                        top1_m                        top1_m                        top1_m                                                          'F'    [106.941581726,286.9559021]
top1_pt                       top1_pt                       top1_pt                       top1_pt                                                         'F'    [10.3063516617,846.840148926]
top1_phi                      top1_phi                      top1_phi                      top1_phi                                                        'F'    [-3.13495254517,3.1372385025]
top2_m                        top2_m                        top2_m                        top2_m                                                          'F'    [90.788444519,282.456939697]
top2_pt                       top2_pt                       top2_pt                       top2_pt                                                         'F'    [4.64201688766,625.037780762]
top2_phi                      top2_phi                      top2_phi                      top2_phi                                                        'F'    [-3.13890004158,3.13752555847]
deltaRb1w1                    deltaRb1w1                    deltaRb1w1                    deltaRb1w1                                                      'F'    [0.0803041085601,3.99765753746]
deltaRb1w2                    deltaRb1w2                    deltaRb1w2                    deltaRb1w2                                                      'F'    [0.130385458469,5.44590520859]
deltaPhiaddw1                 deltaPhiaddw1                 deltaPhiaddw1                 deltaPhiaddw1                                                   'F'    [-3.13872694969,3.13991212845]
deltaPhiaddw2                 deltaPhiaddw2                 deltaPhiaddw2                 deltaPhiaddw2                                                   'F'    [-3.13905572891,3.14076757431]
meanDeltaRbtag                meanDeltaRbtag                meanDeltaRbtag                meanDeltaRbtag                                                  'F'    [0.565383911133,3.34281682968]
prob_chi2                     prob_chi2                     prob_chi2                     prob_chi2                                                       'F'    [1.01478974557e-06,0.996910512447]
BDT_Comb                      BDT_Comb                      BDT_Comb                      BDT_Comb                                                        'F'    [-0.98775780201,0.985033154488]
deltaPhiaddtop1               deltaPhiaddtop1               deltaPhiaddtop1               deltaPhiaddtop1                                                 'F'    [-3.14104366302,3.1355817318]
deltaPhiaddtop2               deltaPhiaddtop2               deltaPhiaddtop2               deltaPhiaddtop2                                                 'F'    [-3.13774347305,3.13699102402]
deltaEtaaddtop2               deltaEtaaddtop2               deltaEtaaddtop2               deltaEtaaddtop2                                                 'F'    [-5.32019901276,5.06106901169]
deltaPhiq1q2                  deltaPhiq1q2                  deltaPhiq1q2                  deltaPhiq1q2                                                    'F'    [-3.07977437973,3.14023971558]
deltaEtaaddtop1               deltaEtaaddtop1               deltaEtaaddtop1               deltaEtaaddtop1                                                 'F'    [-6.38396024704,4.45309400558]
deltaPhiaddb2                 deltaPhiaddb2                 deltaPhiaddb2                 deltaPhiaddb2                                                   'F'    [-3.14032006264,3.14077305794]
deltaPhiaddb1                 deltaPhiaddb1                 deltaPhiaddb1                 deltaPhiaddb1                                                   'F'    [-3.13544225693,3.13973855972]
deltaRaddb1                   deltaRaddb1                   deltaRaddb1                   deltaRaddb1                                                     'F'    [0.411705136299,4.85035896301]
deltaRaddb2                   deltaRaddb2                   deltaRaddb2                   deltaRaddb2                                                     'F'    [0.409183084965,4.95172023773]
deltaPhit1t2                  deltaPhit1t2                  deltaPhit1t2                  deltaPhit1t2                                                    'F'    [-3.13968729973,3.14104151726]
deltaRb1q1                    deltaRb1q1                    deltaRb1q1                    deltaRb1q1                                                      'F'    [0.398122489452,3.55456662178]
deltaRl1l2                    deltaRl1l2                    deltaRl1l2                    deltaRl1l2                                                      'F'    [0.417920440435,3.27634882927]
btagLR4b                      btagLR4b                      btagLR4b                      btagLR4b                                                        'F'    [0.978011667728,0.999990403652]
deltaRb2w2                    deltaRb2w2                    deltaRb2w2                    deltaRb2w2                                                      'F'    [0.111381322145,4.40485525131]
deltaRb2w1                    deltaRb2w1                    deltaRb2w1                    deltaRb2w1                                                      'F'    [0.22263404727,5.90336275101]
btagLR3b                      btagLR3b                      btagLR3b                      btagLR3b                                                        'F'    [0.902796387672,0.997682213783]
deltaEtaw1w2                  deltaEtaw1w2                  deltaEtaw1w2                  deltaEtaw1w2                                                    'F'    [-5.38445520401,5.71565771103]
deltaRb1top2                  deltaRb1top2                  deltaRb1top2                  deltaRb1top2                                                    'F'    [0.0901857763529,6.02286672592]
mindeltaRb1q                  mindeltaRb1q                  mindeltaRb1q                  mindeltaRb1q                                                    'F'    [0.398122489452,3.32949638367]
deltaEtaaddw2                 deltaEtaaddw2                 deltaEtaaddw2                 deltaEtaaddw2                                                   'F'    [-4.05165958405,5.14598369598]
deltaEtaaddw1                 deltaEtaaddw1                 deltaEtaaddw1                 deltaEtaaddw1                                                   'F'    [-5.17343044281,5.42462682724]
deltaRb2p1                    deltaRb2p1                    deltaRb2p1                    deltaRb2p1                                                      'F'    [0.413985997438,3.6559240818]
deltaRb2top1                  deltaRb2top1                  deltaRb2top1                  deltaRb2top1                                                    'F'    [0.140041381121,5.006254673]
aplanarity                    aplanarity                    aplanarity                    aplanarity                                                      'F'    [0.000729009276256,0.331963330507]
p1b2_mass                     p1b2_mass                     p1b2_mass                     p1b2_mass                                                       'F'    [34.3246650696,248.852081299]
centrality                    centrality                    centrality                    centrality                                                      'F'    [0.283793121576,0.95064419508]
deltaEtaq1q2                  deltaEtaq1q2                  deltaEtaq1q2                  deltaEtaq1q2                                                    'F'    [-1.71362411976,2.20361328125]
deltaPhil1l2                  deltaPhil1l2                  deltaPhil1l2                  deltaPhil1l2                                                    'F'    [-3.12561058998,3.06062293053]
deltaEtal1l2                  deltaEtal1l2                  deltaEtal1l2                  deltaEtal1l2                                                    'F'    [-2.02311396599,2.21661138535]
q1b1_mass                     q1b1_mass                     q1b1_mass                     q1b1_mass                                                       'F'    [33.7997245789,251.326202393]
deltaRaddtop2                 deltaRaddtop2                 deltaRaddtop2                 deltaRaddtop2                                                   'F'    [0.0547286979854,6.16727781296]
deltaRaddtop1                 deltaRaddtop1                 deltaRaddtop1                 deltaRaddtop1                                                   'F'    [0.125481411815,6.38837480545]
ht                            ht                            ht                            ht                                                              'F'    [500.159881592,2262.71459961]
deltaPhiw1w2                  deltaPhiw1w2                  deltaPhiw1w2                  deltaPhiw1w2                                                    'F'    [-3.14089941978,3.14104557037]
closest_mass                  closest_mass                  closest_mass                  closest_mass                                                    'F'    [16.5114383698,101.054985046]
deltaPhib1b2                  deltaPhib1b2                  deltaPhib1b2                  deltaPhib1b2                                                    'F'    [-3.13704323769,3.14136338234]
jets_dRavg                    jets_dRavg                    jets_dRavg                    jets_dRavg                                                      'F'    [1.24312376976,2.8373093605]
deltaEtab1b2                  deltaEtab1b2                  deltaEtab1b2                  deltaEtab1b2                                                    'F'    [-3.88414978981,4.09197378159]
meanCSV                       meanCSV                       meanCSV                       meanCSV                                                         'F'    [0.87949180603,0.998259425163]
deltaRb1b2                    deltaRb1b2                    deltaRb1b2                    deltaRb1b2                                                      'F'    [0.407616198063,4.80632686615]
deltaRaddw2                   deltaRaddw2                   deltaRaddw2                   deltaRaddw2                                                     'F'    [0.202150002122,5.77606630325]
deltaRaddw1                   deltaRaddw1                   deltaRaddw1                   deltaRaddw1                                                     'F'    [0.235133543611,5.88103866577]
mindeltaRb2p                  mindeltaRb2p                  mindeltaRb2p                  mindeltaRb2p                                                    'F'    [0.413985997438,3.26935124397]
meanCSVbtag                   meanCSVbtag                   meanCSVbtag                   meanCSVbtag                                                     'F'    [-0.610313713551,0.958395957947]
jets_dRmax                    jets_dRmax                    jets_dRmax                    jets_dRmax                                                      'F'    [2.450091362,5.33998680115]
deltaEtat1t2                  deltaEtat1t2                  deltaEtat1t2                  deltaEtat1t2                                                    'F'    [-5.30541086197,5.48260164261]
deltaRq1q2                    deltaRq1q2                    deltaRq1q2                    deltaRq1q2                                                      'F'    [0.405221045017,3.19342780113]
BDT_CWoLa                     BDT_CWoLa                     BDT_CWoLa                     BDT_CWoLa                                                       'F'    [-0.94276034832,0.989263772964]
addJet_CSV[0]                 addJet_CSV_0_                 addJet_CSV[0]                 addJet_CSV[0]                                                   'F'    [-10,0.999380946159]
addJet_pt[0]                  addJet_pt_0_                  addJet_pt[0]                  addJet_pt[0]                                                    'F'    [30.0188694,916.947631836]
jet_QGL[0]                    jet_QGL_0_                    jet_QGL[0]                    jet_QGL[0]                                                      'F'    [4.00573298975e-06,0.999999940395]
jet_QGL[1]                    jet_QGL_1_                    jet_QGL[1]                    jet_QGL[1]                                                      'F'    [2.86898966806e-07,0.999999880791]
jet_QGL[2]                    jet_QGL_2_                    jet_QGL[2]                    jet_QGL[2]                                                      'F'    [2.41824835712e-07,0.999999582767]
jet_QGL[3]                    jet_QGL_3_                    jet_QGL[3]                    jet_QGL[3]                                                      'F'    [1.79713879334e-07,0.999999821186]
jet_QGL[4]                    jet_QGL_4_                    jet_QGL[4]                    jet_QGL[4]                                                      'F'    [2.62605027501e-07,1]
jet_QGL[5]                    jet_QGL_5_                    jet_QGL[5]                    jet_QGL[5]                                                      'F'    [1.00300601158e-09,1]
jet_CSV[1]                    jet_CSV_1_                    jet_CSV[1]                    jet_CSV[1]                                                      'F'    [0.0651572421193,0.999421477318]
jet_CSV[2]                    jet_CSV_2_                    jet_CSV[2]                    jet_CSV[2]                                                      'F'    [0.0523203983903,0.999436616898]
jet_CSV[3]                    jet_CSV_3_                    jet_CSV[3]                    jet_CSV[3]                                                      'F'    [0.0523599795997,0.999440550804]
jet_CSV[4]                    jet_CSV_4_                    jet_CSV[4]                    jet_CSV[4]                                                      'F'    [0.0531466603279,0.999271392822]
jet_CSV[5]                    jet_CSV_5_                    jet_CSV[5]                    jet_CSV[5]                                                      'F'    [0.0522219277918,0.999441683292]
jet_MOverPt[0]                jet_MOverPt_0_                jet_MOverPt[0]                jet_MOverPt[0]                                                  'F'    [0.03747196123,0.26772198081]
jet_MOverPt[1]                jet_MOverPt_1_                jet_MOverPt[1]                jet_MOverPt[1]                                                  'F'    [0.0529549047351,0.281563580036]
jet_MOverPt[2]                jet_MOverPt_2_                jet_MOverPt[2]                jet_MOverPt[2]                                                  'F'    [0.0618086643517,0.27363961935]
jet_MOverPt[3]                jet_MOverPt_3_                jet_MOverPt[3]                jet_MOverPt[3]                                                  'F'    [0.0631309896708,0.298301577568]
jet_MOverPt[4]                jet_MOverPt_4_                jet_MOverPt[4]                jet_MOverPt[4]                                                  'F'    [0.0444975160062,0.264001756907]
jet_MOverPt[5]                jet_MOverPt_5_                jet_MOverPt[5]                jet_MOverPt[5]                                                  'F'    [0.0644618719816,0.292527526617]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadPyDNN_Multi_n_bjets>=5 : public IClassifierReader {

 public:

   // constructor
   ReadPyDNN_Multi_n_bjets>=5( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadPyDNN_Multi_n_bjets>=5" ),
        fNvars( 96 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "tt_m", "tt_pt", "tt_phi", "tt_eta", "b1_phi", "b1_eta", "b2_phi", "b2_eta", "lq1_phi", "lq2_phi", "lp1_phi", "lp2_phi", "w1_m", "w1_phi", "w2_m", "w2_phi", "top1_m", "top1_pt", "top1_phi", "top2_m", "top2_pt", "top2_phi", "deltaRb1w1", "deltaRb1w2", "deltaPhiaddw1", "deltaPhiaddw2", "meanDeltaRbtag", "prob_chi2", "BDT_Comb", "deltaPhiaddtop1", "deltaPhiaddtop2", "deltaEtaaddtop2", "deltaPhiq1q2", "deltaEtaaddtop1", "deltaPhiaddb2", "deltaPhiaddb1", "deltaRaddb1", "deltaRaddb2", "deltaPhit1t2", "deltaRb1q1", "deltaRl1l2", "btagLR4b", "deltaRb2w2", "deltaRb2w1", "btagLR3b", "deltaEtaw1w2", "deltaRb1top2", "mindeltaRb1q", "deltaEtaaddw2", "deltaEtaaddw1", "deltaRb2p1", "deltaRb2top1", "aplanarity", "p1b2_mass", "centrality", "deltaEtaq1q2", "deltaPhil1l2", "deltaEtal1l2", "q1b1_mass", "deltaRaddtop2", "deltaRaddtop1", "ht", "deltaPhiw1w2", "closest_mass", "deltaPhib1b2", "jets_dRavg", "deltaEtab1b2", "meanCSV", "deltaRb1b2", "deltaRaddw2", "deltaRaddw1", "mindeltaRb2p", "meanCSVbtag", "jets_dRmax", "deltaEtat1t2", "deltaRq1q2", "BDT_CWoLa", "addJet_CSV[0]", "addJet_pt[0]", "jet_QGL[0]", "jet_QGL[1]", "jet_QGL[2]", "jet_QGL[3]", "jet_QGL[4]", "jet_QGL[5]", "jet_CSV[1]", "jet_CSV[2]", "jet_CSV[3]", "jet_CSV[4]", "jet_CSV[5]", "jet_MOverPt[0]", "jet_MOverPt[1]", "jet_MOverPt[2]", "jet_MOverPt[3]", "jet_MOverPt[4]", "jet_MOverPt[5]" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;
      fVmin[32] = 0;
      fVmax[32] = 0;
      fVmin[33] = 0;
      fVmax[33] = 0;
      fVmin[34] = 0;
      fVmax[34] = 0;
      fVmin[35] = 0;
      fVmax[35] = 0;
      fVmin[36] = 0;
      fVmax[36] = 0;
      fVmin[37] = 0;
      fVmax[37] = 0;
      fVmin[38] = 0;
      fVmax[38] = 0;
      fVmin[39] = 0;
      fVmax[39] = 0;
      fVmin[40] = 0;
      fVmax[40] = 0;
      fVmin[41] = 0;
      fVmax[41] = 0;
      fVmin[42] = 0;
      fVmax[42] = 0;
      fVmin[43] = 0;
      fVmax[43] = 0;
      fVmin[44] = 0;
      fVmax[44] = 0;
      fVmin[45] = 0;
      fVmax[45] = 0;
      fVmin[46] = 0;
      fVmax[46] = 0;
      fVmin[47] = 0;
      fVmax[47] = 0;
      fVmin[48] = 0;
      fVmax[48] = 0;
      fVmin[49] = 0;
      fVmax[49] = 0;
      fVmin[50] = 0;
      fVmax[50] = 0;
      fVmin[51] = 0;
      fVmax[51] = 0;
      fVmin[52] = 0;
      fVmax[52] = 0;
      fVmin[53] = 0;
      fVmax[53] = 0;
      fVmin[54] = 0;
      fVmax[54] = 0;
      fVmin[55] = 0;
      fVmax[55] = 0;
      fVmin[56] = 0;
      fVmax[56] = 0;
      fVmin[57] = 0;
      fVmax[57] = 0;
      fVmin[58] = 0;
      fVmax[58] = 0;
      fVmin[59] = 0;
      fVmax[59] = 0;
      fVmin[60] = 0;
      fVmax[60] = 0;
      fVmin[61] = 0;
      fVmax[61] = 0;
      fVmin[62] = 0;
      fVmax[62] = 0;
      fVmin[63] = 0;
      fVmax[63] = 0;
      fVmin[64] = 0;
      fVmax[64] = 0;
      fVmin[65] = 0;
      fVmax[65] = 0;
      fVmin[66] = 0;
      fVmax[66] = 0;
      fVmin[67] = 0;
      fVmax[67] = 0;
      fVmin[68] = 0;
      fVmax[68] = 0;
      fVmin[69] = 0;
      fVmax[69] = 0;
      fVmin[70] = 0;
      fVmax[70] = 0;
      fVmin[71] = 0;
      fVmax[71] = 0;
      fVmin[72] = 0;
      fVmax[72] = 0;
      fVmin[73] = 0;
      fVmax[73] = 0;
      fVmin[74] = 0;
      fVmax[74] = 0;
      fVmin[75] = 0;
      fVmax[75] = 0;
      fVmin[76] = 0;
      fVmax[76] = 0;
      fVmin[77] = 0;
      fVmax[77] = 0;
      fVmin[78] = 0;
      fVmax[78] = 0;
      fVmin[79] = 0;
      fVmax[79] = 0;
      fVmin[80] = 0;
      fVmax[80] = 0;
      fVmin[81] = 0;
      fVmax[81] = 0;
      fVmin[82] = 0;
      fVmax[82] = 0;
      fVmin[83] = 0;
      fVmax[83] = 0;
      fVmin[84] = 0;
      fVmax[84] = 0;
      fVmin[85] = 0;
      fVmax[85] = 0;
      fVmin[86] = 0;
      fVmax[86] = 0;
      fVmin[87] = 0;
      fVmax[87] = 0;
      fVmin[88] = 0;
      fVmax[88] = 0;
      fVmin[89] = 0;
      fVmax[89] = 0;
      fVmin[90] = 0;
      fVmax[90] = 0;
      fVmin[91] = 0;
      fVmax[91] = 0;
      fVmin[92] = 0;
      fVmax[92] = 0;
      fVmin[93] = 0;
      fVmax[93] = 0;
      fVmin[94] = 0;
      fVmax[94] = 0;
      fVmin[95] = 0;
      fVmax[95] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';
      fType[33] = 'F';
      fType[34] = 'F';
      fType[35] = 'F';
      fType[36] = 'F';
      fType[37] = 'F';
      fType[38] = 'F';
      fType[39] = 'F';
      fType[40] = 'F';
      fType[41] = 'F';
      fType[42] = 'F';
      fType[43] = 'F';
      fType[44] = 'F';
      fType[45] = 'F';
      fType[46] = 'F';
      fType[47] = 'F';
      fType[48] = 'F';
      fType[49] = 'F';
      fType[50] = 'F';
      fType[51] = 'F';
      fType[52] = 'F';
      fType[53] = 'F';
      fType[54] = 'F';
      fType[55] = 'F';
      fType[56] = 'F';
      fType[57] = 'F';
      fType[58] = 'F';
      fType[59] = 'F';
      fType[60] = 'F';
      fType[61] = 'F';
      fType[62] = 'F';
      fType[63] = 'F';
      fType[64] = 'F';
      fType[65] = 'F';
      fType[66] = 'F';
      fType[67] = 'F';
      fType[68] = 'F';
      fType[69] = 'F';
      fType[70] = 'F';
      fType[71] = 'F';
      fType[72] = 'F';
      fType[73] = 'F';
      fType[74] = 'F';
      fType[75] = 'F';
      fType[76] = 'F';
      fType[77] = 'F';
      fType[78] = 'F';
      fType[79] = 'F';
      fType[80] = 'F';
      fType[81] = 'F';
      fType[82] = 'F';
      fType[83] = 'F';
      fType[84] = 'F';
      fType[85] = 'F';
      fType[86] = 'F';
      fType[87] = 'F';
      fType[88] = 'F';
      fType[89] = 'F';
      fType[90] = 'F';
      fType[91] = 'F';
      fType[92] = 'F';
      fType[93] = 'F';
      fType[94] = 'F';
      fType[95] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadPyDNN_Multi_n_bjets>=5() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[96];
   double fVmax[96];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[96];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   inline double ReadPyDNN_Multi_n_bjets>=5::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
