// Class: ReadPyDNN_Multi_2ad
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : PyKeras::PyDNN_Multi_2ad
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/04       [396292]
Creator        : viniciusmikuni
Date           : Tue Feb 27 11:54:25 2018
Host           : Darwin Viniciuss-MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
Dir            : /Users/viniciusmikuni/cernbox/CMS/ttbbAnalysis/KinFitter/test/MVA/BDT
Training events: 13564
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
FilenameModel: "models/model_Multi_2ad.h5" [Filename of the initial Keras model]
BatchSize: "128" [Training batch size]
NumEpochs: "200" [Number of training epochs]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
FilenameTrainedModel: "MVA_weights/weights/TrainedModel_PyDNN_Multi_2ad.h5" [Filename of the trained output Keras model]
Verbose: "1" [Keras verbosity during training]
ContinueTraining: "False" [Load weights from previous training]
SaveBestOnly: "True" [Store only weights with smallest validation loss]
TriesEarlyStopping: "-1" [Number of epochs with no improvement in validation loss after which training will be stopped. The default or a negative number deactivates this option.]
LearningRateSchedule: "" [Set new learning rate during training at specific epochs, e.g., "50,0.01;70,0.005"]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 33
deltaRaddb1                   deltaRaddb1                   deltaRaddb1                   deltaRaddb1                                                     'F'    [0.406426757574,5.4088010788]
deltaRaddb2                   deltaRaddb2                   deltaRaddb2                   deltaRaddb2                                                     'F'    [0.403598755598,5.56675004959]
deltaRaddw1                   deltaRaddw1                   deltaRaddw1                   deltaRaddw1                                                     'F'    [0.028237901628,6.95634698868]
deltaRaddw2                   deltaRaddw2                   deltaRaddw2                   deltaRaddw2                                                     'F'    [0.0468369498849,7.8761639595]
deltaRaddtop1                 deltaRaddtop1                 deltaRaddtop1                 deltaRaddtop1                                                   'F'    [0.0283177439123,6.833319664]
deltaRaddtop2                 deltaRaddtop2                 deltaRaddtop2                 deltaRaddtop2                                                   'F'    [0.0343036390841,8.14742660522]
deltaPhiaddb1                 deltaPhiaddb1                 deltaPhiaddb1                 deltaPhiaddb1                                                   'F'    [-3.14123749733,3.14139389992]
deltaPhiaddb2                 deltaPhiaddb2                 deltaPhiaddb2                 deltaPhiaddb2                                                   'F'    [-3.14129328728,3.14145278931]
deltaPhiaddw1                 deltaPhiaddw1                 deltaPhiaddw1                 deltaPhiaddw1                                                   'F'    [-3.14140796661,3.14150810242]
deltaPhiaddw2                 deltaPhiaddw2                 deltaPhiaddw2                 deltaPhiaddw2                                                   'F'    [-3.14134192467,3.14127588272]
deltaPhiaddtop1               deltaPhiaddtop1               deltaPhiaddtop1               deltaPhiaddtop1                                                 'F'    [-3.14104366302,3.14133691788]
deltaPhiaddtop2               deltaPhiaddtop2               deltaPhiaddtop2               deltaPhiaddtop2                                                 'F'    [-3.14133358002,3.14098477364]
deltaEtaaddb1                 deltaEtaaddb1                 deltaEtaaddb1                 deltaEtaaddb1                                                   'F'    [-4.62874031067,4.75467681885]
deltaEtaaddb2                 deltaEtaaddb2                 deltaEtaaddb2                 deltaEtaaddb2                                                   'F'    [-4.6631975174,4.68440485001]
deltaEtaaddw1                 deltaEtaaddw1                 deltaEtaaddw1                 deltaEtaaddw1                                                   'F'    [-6.90462255478,6.41151952744]
deltaEtaaddw2                 deltaEtaaddw2                 deltaEtaaddw2                 deltaEtaaddw2                                                   'F'    [-5.19818305969,7.35691833496]
deltaEtaaddtop1               deltaEtaaddtop1               deltaEtaaddtop1               deltaEtaaddtop1                                                 'F'    [-6.58418560028,5.92966651917]
deltaEtaaddtop2               deltaEtaaddtop2               deltaEtaaddtop2               deltaEtaaddtop2                                                 'F'    [-8.12321853638,6.05837631226]
addJet_CSV[0]                 addJet_CSV_0_                 addJet_CSV[0]                 addJet_CSV[0]                                                   'F'    [0.0418400205672,0.999540448189]
ht                            ht                            ht                            ht                                                              'F'    [500.011352539,2536.46411133]
btagLR4b                      btagLR4b                      btagLR4b                      btagLR4b                                                        'F'    [0.945410311222,0.999990403652]
btagLR3b                      btagLR3b                      btagLR3b                      btagLR3b                                                        'F'    [0.864528656006,0.997682213783]
BDT_CWoLa                     BDT_CWoLa                     BDT_CWoLa                     BDT_CWoLa                                                       'F'    [-0.947920978069,0.992888092995]
BDT_Comb                      BDT_Comb                      BDT_Comb                      BDT_Comb                                                        'F'    [-0.997045397758,0.985813200474]
BDT_FullQCD                   BDT_FullQCD                   BDT_FullQCD                   BDT_FullQCD                                                     'F'    [-0.804049730301,0.970019102097]
meanCSV                       meanCSV                       meanCSV                       meanCSV                                                         'F'    [0.858942627907,0.998025238514]
meanDeltaRbtag                meanDeltaRbtag                meanDeltaRbtag                meanDeltaRbtag                                                  'F'    [0.565383911133,3.80512237549]
addJet_deltaR                 addJet_deltaR                 addJet_deltaR                 addJet_deltaR                                                   'F'    [0,5.43131828308]
addJet_deltaPhi               addJet_deltaPhi               addJet_deltaPhi               addJet_deltaPhi                                                 'F'    [-3.14111661911,3.14115834236]
addJet_deltaEta               addJet_deltaEta               addJet_deltaEta               addJet_deltaEta                                                 'F'    [-4.70644378662,4.64183282852]
addJet_CSV[1]                 addJet_CSV_1_                 addJet_CSV[1]                 addJet_CSV[1]                                                   'F'    [-10,0.999617755413]
addJet_pt[1]                  addJet_pt_1_                  addJet_pt[1]                  addJet_pt[1]                                                    'F'    [0,934.544372559]
addJet_mass                   addJet_mass                   addJet_mass                   addJet_mass                                                     'F'    [0,2846.53222656]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadPyDNN_Multi_2ad : public IClassifierReader {

 public:

   // constructor
   ReadPyDNN_Multi_2ad( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadPyDNN_Multi_2ad" ),
        fNvars( 33 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "deltaRaddb1", "deltaRaddb2", "deltaRaddw1", "deltaRaddw2", "deltaRaddtop1", "deltaRaddtop2", "deltaPhiaddb1", "deltaPhiaddb2", "deltaPhiaddw1", "deltaPhiaddw2", "deltaPhiaddtop1", "deltaPhiaddtop2", "deltaEtaaddb1", "deltaEtaaddb2", "deltaEtaaddw1", "deltaEtaaddw2", "deltaEtaaddtop1", "deltaEtaaddtop2", "addJet_CSV[0]", "ht", "btagLR4b", "btagLR3b", "BDT_CWoLa", "BDT_Comb", "BDT_FullQCD", "meanCSV", "meanDeltaRbtag", "addJet_deltaR", "addJet_deltaPhi", "addJet_deltaEta", "addJet_CSV[1]", "addJet_pt[1]", "addJet_mass" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;
      fVmin[30] = 0;
      fVmax[30] = 0;
      fVmin[31] = 0;
      fVmax[31] = 0;
      fVmin[32] = 0;
      fVmax[32] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';
      fType[30] = 'F';
      fType[31] = 'F';
      fType[32] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadPyDNN_Multi_2ad() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[33];
   double fVmax[33];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[33];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   inline double ReadPyDNN_Multi_2ad::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
