samples=['QCD','ttbb','tt2b','ttb']
sys_list=[
    '_lumi',
    '_pdf_gg',
    '_pdf_qqbar',
    '_pdf_qg',
    '_QCD_scale_ttH',
    '_QCD_scale_tt',
    '_QCD_scale_t',
    '_QCD_scale_V',
    '_QCD_scale_VV',
    '_bgnorm_ttbarPlusCCbar',
    '_bgnorm_ttbb',
    '_bgnorm_tt2b',
    '_bgnorm_ttb',
    '_ttbb_FSR',
    '_ttbb_ISR',
    '_ttbb_tune',
    '_ttbb_hdamp',
    '_tt2b_FSR',
    '_tt2b_ISR',
    '_tt2b_tune',
    '_tt2b_hdamp',
    '_ttb_FSR',
    '_ttb_ISR',
    '_ttb_tune',
    '_ttb_hdamp',
    '_ttlf_FSR',
    '_ttlf_ISR',
    '_ttlf_tune',
    '_ttlf_hdamp',
    '_ttcc_FSR',
    '_ttcc_ISR',
    '_ttcc_tune',
    '_ttcc_hdamp',
    '_CMS_btag_hf',
    '_CMS_btag_cferr1',
    '_CMS_btag_cferr2',
    '_CMS_btag_lf',
    '_CMS_btag_lfstats2',
    '_CMS_btag_lfstats1',
    '_CMS_btag_hfstats2',
    '_CMS_btag_hfstats1',
    '_CMS_btag_jes',
    '_CMS_pu_Weight',
    '_CMS_top_Weight',
    '_CMS_qg_Weight',
    '_CMS_trig_Weight',
    '_CMS_RelativeStatEC_j',
    '_CMS_RelativeStatHF_j',
    '_CMS_PileUpDataMC_j',
    '_CMS_PileUpPtRef_j',
    '_CMS_PileUpPtBB_j',
    '_CMS_PileUpPtEC1_j',
    '_CMS_PileUpPtEC2_j',
    '_CMS_PileUpPtHF_j',
    '_CMS_RelativeStatFSR_j',
    '_CMS_RelativeFSR_j',
    '_CMS_AbsoluteScale_j',
    '_CMS_AbsoluteFlavMap_j',
    '_CMS_AbsoluteMPFBias_j',
    '_CMS_Fragmentation_j',
    '_CMS_SinglePionECAL_j',
    '_CMS_SinglePionHCAL_j',
    '_CMS_FlavorQCD_j',
    '_CMS_TimePtEta_j',
    '_CMS_RelativeJEREC1_j',
    '_CMS_RelativeJEREC2_j',
    '_CMS_RelativeJERHF_j',
    '_CMS_RelativePtBB_j',
    '_CMS_RelativePtEC1_j',
    '_CMS_RelativePtEC2_j',
    '_CMS_RelativePtHF_j',
    '_CMS_SubTotalPileUp_j',
    '_CMS_JER_j',
    '_CMS_AbsoluteStat_j',
    '_CMS_Total_j'
]
with open('figs.tex','w') as f:
    for sys in sys_list:
        fig = r"\begin{figure}[hbtp]"
        fig+="\n"
        fig+= "\t\centering\n"
        for sample in samples:
            fig+= "\t"
            fig+= r"\includegraphics[width=0.24\textwidth]{Sys_app/"+sample+sys+"Up}\n"
        fig+= "\end{figure}\n"
        print fig
        f.write(fig)
